[plasmicpkgs] Replacing camelcase package by change-case package
camelcase package doesn’t work in browsers

Error: require() of ES Module /home/abudkhamid/Documents/plasmic-test/node_modules/camelcase/index.js from /home/abudkhamid/Documents/plasmic-test/node_modules/@plasmicpkgs/plasmic-contentful/dist/plasmic-contentful.cjs.development.js not supported.
Instead change the require index.js in /home/abdukhamid/Documents/plasmic-test/node_modules/@plasmicpkgs/plasmic-contentful/dist/plasmic-contentful.cjs.development.js to a dynamic import() which is available in all CommonJs modules.
https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491

Changing for change-case: https://www.npmjs.com/package/change-case

Packages unpacked size:

camelcase: 11.5kb 
change-case: 9.33kb

Change-Id: Ia3732ad728f1a56905af53b9081031243c05ccfe